[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
sapphire-testnet = "https://testnet.sapphire.oasis.io"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
